services:
  mysql:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    environment:
      - 'MYSQL_DATABASE=booking-database'
      - 'MYSQL_PASSWORD=Mysql123#@!'
      - 'MYSQL_USER=mysqluser'
      - 'MYSQL_ROOT_PASSWORD=Root123#@!'
    ports:
      - "3306:3306"

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/booking-database?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: mysqluser
      SPRING_DATASOURCE_PASSWORD: Mysql123#@!