version: '3.7'

services:
  db1:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=client

networks:
  ecommerce-network:
    driver: bridge